### ISSUE TITLE
supported extended flags for Kernel traces

### ISSUE THREAD

**Issue by jdu2600** [microsoft/krabsetw#106]
Some kernel events can't be enabled via the flags in the EVENT_TRACE_PROPERTIES passed to StartTrace() and instead require a subsequent call to TraceSetInformation()

Reference: https://docs.microsoft.com/en-us/windows/win32/etw/obtrace
> To enable object manager event tracing, call the TraceSetInformation function with the InformationClass parameter equal to the TRACE_INFO_CLASS enumeration value TraceSystemTraceEnableFlagsInfo and the EVENT_TRACE_PROPERTIES structure's EnableFlags member equal to PERF_OB_HANDLE (0x80000040).

However TraceSetInformation(TraceSystemTraceEnableFlagsInfo ) errored with 'invalid parameter' whenever I passed an EVENT_TRACE_PROPERTIES. It succeeds when I pass a PERFINFO_GROUPMASK instead.
See https://geoffchappell.com/studies/windows/km/ntoskrnl/api/etw/tracesup/perfinfo_groupmask.htm

**Comment by jdu2600** [comment]
I also defined all of the kernel guids defined in the MSNT_SystemTrace WMI class as of Windows 10 1909.

See https://gist.github.com/jdu2600/a2b03e4e9cf19282a41ad766388c9856

**Comment by swannman** [comment]
Resolved by #107
