### ISSUE TITLE
Latest changes break compatibility with Windows 7

### ISSUE THREAD

**Issue by jrave** [microsoft/krabsetw#109]
Changes in #107 cause incompatibility of krabs on Windows 7. Specifically it is related to the usage of TraceQueryInformation API which is only supported on Windows 8 and newer: https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-tracequeryinformation

@jdu2600 : Do you think it would be possible to rework that change to not rely on this API?

**Comment by jdu2600** [comment]
TraceSetInformation is a light wrapper around NtSetSystemInformation - which provides an alternate approach to supporting Windows 7.  

See https://geoffchappell.com/studies/windows/km/ntoskrnl/api/etw/tracesup/groupmask.htm

**Comment by swannman** [comment]
Fixed by #113
