### ISSUE TITLE
ANDing/ORing predicates could be better

### ISSUE THREAD

**Issue by pathtofile** [microsoft/krabsetw#122]
There is two predicates `and_filter` and `or_filter` that enable two predicates to be 'chained' togther, but they only take in 2 predicates.
To compare 3+ at once requires chaining these functions in a way that looks ugly and is inefficient, particularly if generating the 'chain' dynamically.

An example use case may be to listen to `Microsoft-Windows-Kernel-Process` for process exits where `ImageName == foo.exe && ExitCode != 0 && TokenElevationType == 2`.
Another example may be to give a vector list of 30 different opcodes to monitor for.

It would be nice if there was a predicate that takes in a list of predicates, that are all compared at once. I had a first attempt at doing this, creating functions that take in a vector list: MR: https://github.com/microsoft/krabsetw/pull/121 (the merge has a new example demonstrating it's use: `user_trace_006_predicate_vectors`)

If you are happy with this inclusion I can make sure theres unit tests, ect for it. Otherwise I'm happy to keep this code in my own system.

**Comment by pathtofile** [comment]
Also if you feel that this is unneeded, happy to see examples of a better way to this sort of chaining currently.

**Comment by swannman** [comment]
Hi @pathtofile, your approach sounds reasonable. Here's how this would be done today:

![image](https://user-images.githubusercontent.com/830389/79165368-d678dc00-7d97-11ea-8f15-69340f9fb440.png)

...but as you observed, if you want to `and` or `or` more than two items, it quickly becomes unwieldy. 

Callers using the managed krabs API are able to do this more elegantly using fluent syntax:

![image](https://user-images.githubusercontent.com/830389/79165831-cd3c3f00-7d98-11ea-9a62-321b251303c4.png)

Could you go ahead and add unit tests and an example to your PR? Thanks!

**Comment by pathtofile** [comment]
Done, added it all into a PR here: https://github.com/microsoft/krabsetw/pull/124

**Comment by pathtofile** [comment]
Now merged, so closing request, thanks!
