### ISSUE TITLE
Enabling a trace when there are no more sessions available fails silently

### ISSUE THREAD

**Issue by kallanreed** [Microsoft/krabsetw#13]
1  Run the test app creating a new GUID session each time.
2  Verify the trace is receiving events.
3  Kill the test app (instead of allowing dtors tor run)
4  Repeat until eventually step 2 fails because the session hasn't actually started/registered properly.

Workaround: delete the stale trace sessions.

We should fail with an error or something that will let the caller know the session isn't set up properly.

**Comment by zacbrown** [comment]
Fixed in 3dff28a.
