### ISSUE TITLE
Error Not Found when trying to parse events from SCM provider

### ISSUE THREAD

**Issue by bclin717** [microsoft/krabsetw#136]
Hi, I have a problem parsing events provided by SCM provider {555908d1-a6d7-4695-8e1e-26931d2012f4} .
krabs::could_not_find_schema() is thrown because tdhGetEventInformation() (schema_locator.hpp line:138) returns error 1168.
I found that there are all zero in the record->EventHeader->EventDescriptor in the events, so tdhGetEventInformation() can't parse without event id.

![](https://i.imgur.com/xuV4Eo1.jpg)

I was wondering if there's any way to parse event properties in the event provided by SCM provider.
Thanks!

**Comment by obfuscatedbytes** [comment]
Note: the `LEGACY_EVENTLOG` flag is set for SCM events, which indicates that you need a WMI MOF class to parse the event data.

I've had issues with the TDH call failing for other providers as well, and while there may be a solution using Krabs that I overlooked, I ended up just implementing the trace controller and consumer using the ETW API directly.

https://docs.microsoft.com/en-us/windows/win32/etw/retrieving-event-data-using-mof
