### ISSUE TITLE
how to get old_file_name, new_file_name from rename event in etw

### ISSUE THREAD

**Issue by yangjian123** [microsoft/krabsetw#152]
i want to use krabsetw to monitor fileio event , include create,delete, read, write,rename, but how can i get new_file_name, old_file_name,does krabsetw supply this feature?

**Comment by jdu2600** [comment]
Suggest looking at event 19 (Rename) and event 29 (Rename29) in the Microsoft-Windows-Kernel-File provider.

You might need to resolve FileObject and FileKey pointers to file names. Some hints for that are here - https://lowleveldesign.org/2020/08/15/fixing-empty-paths-in-fileio-events-etw/
