### ISSUE TITLE
Microsoft-Windows-Security-Auditing not work on some versions

### ISSUE THREAD

**Issue by zeze-zeze** [microsoft/krabsetw#157]
I tested the Microsoft-Windows-Security-Auditing in user_trace_005.cpp, which could work in Windows10 19042.928 (host), while it aborted when using Windows Server 2012, Windows 7, Windows10 1079 (vm using vmware). 

In all of the tests I used system privilege to run the program.

Any clue would be grateful !

**Comment by zeze-zeze** [comment]
It turned out that the reason that cause the error was because the error code returned from ControlTrace().
According to [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-controltracea), we can find what error code means.
In Windows10 19042.928, it returns 5, which corresponds to ERROR_ACCESS_DENIED.
In Windows Server 2012 and Windows10 1079, it returns 87, which corresponds to ERROR_INVALID_PARAMETER.

However, I still don't know why the error codes returned are different.

**Comment by swannman** [comment]
Resolved by #158 - thanks @zeze-zeze !
