### ISSUE TITLE
Lobsters examples seems outated

### ISSUE THREAD

**Issue by rafaelvascc** [Microsoft/krabsetw#2]
Hi Zac, i was trying to use the lobster examples and Visual Studio displayed the following errors:

1. The delegate in "powershellProvider.OnEvent += (EventRecord record)" expects IEventRecord, not EventRecord

2. I coudn't find the classes Schema and Parser. If i have to implement those classes, could you please provide an example of how to do it? 

I'm new to ETW by the way, thanks for your lib.

**Comment by zacbrown** [comment]
Ah yep. I will update that today. Thanks for pointing that out!

**Comment by zacbrown** [comment]
By the way, this example may get you further faster: https://github.com/zacbrown/PowerShellMethodAuditor

**Comment by rafaelvascc** [comment]
Alright, thanks for the quick reply Zac. :)

**Comment by zacbrown** [comment]
This is now fixed as of 0 minutes ago :). Please let me know if you continue to see issues.
