### ISSUE TITLE
No proper explanation for kernel_trace vs user_trace?

### ISSUE THREAD

**Issue by subvert0r** [microsoft/krabsetw#218]
I am very confused on the difference between krabs::user_trace vs  krabs::kernel_trace and its not properly explained in the docs.

I have used user_trace so far, and was able to receive events from any provider that I have tried, including those that have kernel in their name such as "Microsoft-Windows-Kernel-Process".

So what's the difference between them exactly? when should I use krabs::kernel_trace?

**Comment by swannman** [comment]
Good question! The "kernel trace" refers to events that are emitted by the Windows kernel through the [NT Kernel Logger Session](https://learn.microsoft.com/en-us/windows/win32/etw/configuring-and-starting-the-nt-kernel-logger-session). The `EnableFlags` values [here](https://learn.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties) show the types of data that are emitted by this provider.
