### ISSUE TITLE
Benefits and drawbacks of using a kernel_trace vs a user_trace for consuming an event which is in both?

### ISSUE THREAD

**Issue by subvert0r** [microsoft/krabsetw#220]
Some events can be consumed both with a kernel_trace and also a user_trace.

For example the process event, which can be consumed both with the kernel_trace using krabs::guids::process, and also with a user_trace using Microsoft-Windows-Kernel-Process.  

Any benefit of using a kernel_trace for these vs using a user_trace? What about the drawbacks?

I think the docs should get updated to explain more regarding the differences between the user_trace and kernel_trace.

**Comment by swannman** [comment]
Although some events are emitted in both [the kernel debug trace session](https://github.com/microsoft/krabsetw/issues/218) and a user-mode trace session, they may not have the same information. For example, the process start events emitted by the kernel debug trace session contain the process command line, but the Microsoft-Windows-Kernel-Process provider spreads the process start and command line information across two event types that must be correlated together. 

In general, I would recommend using a user-mode trace session unless you need to subscribe to an event that can only be found on the kernel debug trace session.

**Comment by swannman** [comment]
Yes, it's possible for there to be a performance impact when enabling any ETW provider. Windows components typically check whether any trace sessions have subscribed to their ETW provider + enabled the appropriate keywords for tracing; if none are subscribed, they skip emitting the event.

In practice, the overhead of simply emitting an ETW event is imperceptible in both the kernel and user-mode case. However, applications may choose to enable more expensive diagnostics when an ETW provider is enabled. For example, several years ago we observed a severe performance impact when enabling verbose tracing for SQL Server queries. I would be most concerned about this when enabling ETW providers that are not part of the core Windows operating system.

**Comment by swannman** [comment]
> Which of these two will impact the performance of the machine more?

In my experience I have not observed any performance impact from either of your 2 scenarios, and have not observed any difference between them.
