### ISSUE TITLE
Does krabs c++ library support c++11? What about v120 platform toolset?

### ISSUE THREAD

**Issue by subvert0r** [microsoft/krabsetw#223]
As the title says, my question is does krabs c++ library support c++11? Or does it require a newer c++ version?

Also can I face any issues if I Include krabs in a c++ visual studio 2013 project which has enabled Windows XP (v120) as its platform toolset (so it would be able to run in the pre vista machines) ? 
**Obviously in these ancient machines I wouldn't want to use krabs ETW**, but just want my project to be able to run in XP machines for other features that my project has, and would not use ETW in these scenarios. (I have already changes the krabs to load vista+ API functions dynamically) And I dont want to have a separate build for xp machines.

**Comment by swannman** [comment]
The krabsetw library has a C++17 dependency today (see #51). We haven't tested building in a C++11 context or in VS2013, but feel free to fork the project and make targeted changes where needed.
