### ISSUE TITLE
NuGet feeds are not compliant with NuGet feed security requirements

### ISSUE THREAD

**Issue by matt-vanderkolk** [microsoft/krabsetw#233]
We're trying to ingest this feed into a Component Governance controlled pipeline and we are hitting errors because there are 2 NuGet feeds which point directly to nuget.org. Our partner's requirements state this must be directed through an ADO artifact feed. Is this something you can set up? Please reach out to me directly for more context.

**Comment by swannman** [comment]
Moved this to an internal discussion and shared steps for creating an [artifact feed](https://learn.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=windows#create-a-feed) that consumes from upstream sources.
