### ISSUE TITLE
what is object_manager_provider?

### ISSUE THREAD

**Issue by Kwansy98** [microsoft/krabsetw#248]
Hello, can anyone explain the statement "record.EventHeader.EventDescriptor.Opcode == 33" in the kernel_trace_002::start() function? What does the number 33 mean? And why is there an "ObjectName" property in it? I can't find the provider 89497f50-effe-4440-8cf2-ce6b1cdcaca7 using etw explorer or logman query providers. Thanks!

https://github.com/microsoft/krabsetw/blob/4b1456c39a6f4e8e934d3952dc37bfa6564a62fa/examples/NativeExamples/kernel_trace_002.cpp#L23

**Comment by swannman** [comment]
Hi @Kwansy98, we aren't able to assist with individual ETW providers. I do see a public reference here that may be relevant: https://gist.github.com/jdu2600/a2b03e4e9cf19282a41ad766388c9856#file-windowskerneltrace-mof-L157

**Comment by Kwansy98** [comment]
> Hi [@Kwansy98](https://github.com/Kwansy98), we aren't able to assist with individual ETW providers. I do see a public reference here that may be relevant: https://gist.github.com/jdu2600/a2b03e4e9cf19282a41ad766388c9856#file-windowskerneltrace-mof-L157

Thanks for the guidance
