### ISSUE TITLE
Use with Powershell

### ISSUE THREAD

**Issue by KurtDeGreeff** [Microsoft/krabsetw#31]
Dear, is it possible to use this library from Powershell?
If so, would you be so kind to provide some examples..

**Comment by zacbrown** [comment]
Hi Kurt,

It is possible but it's not very convenient in the core krabsetw/O365.Security.ETW library.

I'm actually working on a separate project to expose a more friendly API for it called PowerKrabsEtw. The library should be open source in the next few days.

You'll be able to find it on my github account (https://github.com/zacbrown).

-Zac

**Comment by KurtDeGreeff** [comment]
Hi Zac,
Ok great news, I'm looking forward to try it out

Thanks a lot

**Comment by zacbrown** [comment]
@KurtDeGreeff  - I've released the alpha version of PowerKrabsEtw here: https://github.com/zacbrown/PowerKrabsEtw
