### ISSUE TITLE
compilation errors in the library

### ISSUE THREAD

**Issue by chrisrollins** [Microsoft/krabsetw#37]
Hi, I'm trying to get the C++ version to compile, but I'm getting some errors from the library's code.

line 100 of kt.hpp
C2440 'return': cannot convert from 'const char [17]' to 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>'

```
 inline const std::wstring kt::enforce_name_policy(
        const std::wstring &name_hint)
    {
        if (IsWindows8OrGreater()) {
            return krabs::details::ut::enforce_name_policy(name_hint);
        }

        return KERNEL_LOGGER_NAME;
    }
```

Fixing that is simple, I can change it to 
return KERNEL_LOGGER_NAMEW;

After fixing that, there are 3 errors in nightmare.hpp, also type errors, so that's probably not the end of it.

Did I miss a crucial step for getting the library to compile?

**Comment by zacbrown** [comment]
Hi,

Sounds like you’re missing an include for wchar.h. I can make that a more explicit part of the headers as well as add it to the requirements list. 

Krabs is written largely for a WCHAR context aside from properties that are explicitly ASCII strings. 

-Zac

**Comment by chrisrollins** [comment]
Hi Zac. Thanks for the response.

I added #include <wchar.h> but I'm still getting the type errors from krabs.

- Chris

**Comment by zacbrown** [comment]
Could you attach a single file of code that shows the issue?

What version of VS are you using to compile the code?

-Zac

**Comment by chrisrollins** [comment]
Update: I figured it out. I needed to define UNICODE in my project. Not sure if you have this anywhere in the requirements but I may have missed it.

-Chris

**Comment by zacbrown** [comment]
Looks like we don't have that outlined anywhere. I'll make a note in the compilation notes. Thanks!
