### ISSUE TITLE
Possible bugs when capturing events.

### ISSUE THREAD

**Issue by rafaelvascc** [Microsoft/krabsetw#4]
Hi again Zac.
I'm having a strange result when trying to use lobster to process the events of a example EventSource i made.

Here is the event source and console aplication that runs it:

```
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ETWeEnerator
{
    [EventSource(Name = "EventTrigger", Guid = "835828ae-38d2-51c8-51b8-0a6ee280d4a8")]
    public sealed class EventTrigger : EventSource
    {
        public class Keywords
        {
            public const EventKeywords Network = (EventKeywords)1;
            public const EventKeywords Database = (EventKeywords)2;
            public const EventKeywords Diagnostics = (EventKeywords)4;
            public const EventKeywords Performance = (EventKeywords)8;
        }

        public class Taks
        {
            public const EventTask LogInfo = (EventTask)1;
            public const EventTask LogError = (EventTask)2;
        }

        public class Tags
        {
            public const EventTags Info = (EventTags)1;
            public const EventTags Error = (EventTags)2;
        }

        public EventTrigger() : base("EventTrigger")
        {
        }

        public static EventTrigger Log = new EventTrigger();

        [Event(1, Opcode = EventOpcode.Info, Level = EventLevel.Informational, Keywords = Keywords.Network, Message = "{0}", Tags = Tags.Info)]
        public void LogEvent(string message)
        {
            base.WriteEvent(1, message);
        }

        [Event(2, Opcode = EventOpcode.Info, Level = EventLevel.Error, Keywords = Keywords.Network, Message = "{0}", Tags = Tags.Error)]
        public void LogError(string message, string ex)
        {
            base.WriteEvent(2, message, ex);
        }
    }
}
```

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ETWeEnerator
{
    public class Program
    {
        private static void RaiseEvents()
        {
            Console.WriteLine("Loging info");
            EventTrigger.Log.LogEvent("Some message");
            Console.WriteLine("Creating Error");
            try
            {
                throw new Exception("Some exception");
            }
            catch (Exception ex)
            {
                EventTrigger.Log.LogError("some error", ex.Message);
            }
            Console.WriteLine("Finished");
            Console.ReadKey();
            RaiseEvents();
        }

        public static void Main(string[] args)
        {
            Console.WriteLine("Starting");
            Console.WriteLine("Creating Xml");
            string xml = EventTrigger.GenerateManifest(typeof(EventTrigger), ".");
            File.WriteAllText("eventrigger.xml", xml);
            RaiseEvents();
        }
    }
}
```

And here is the lobster consumer:

```
using O365.Security.ETW;
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Testing = O365.Security.ETW.Testing;

namespace krabs462
{
    public class EventTrigger : EventListener
    {
        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            Console.WriteLine(eventData.EventId);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var trace = new UserTrace();
            
            var provider = new Provider(Guid.Parse("{835828ae-38d2-51c8-51b8-0a6ee280d4a8}"));
            
            provider.Any = Provider.AllBitsSet;
            
            provider.OnEvent += (IEventRecord record) =>
            {

                if (record.Id == 1)
                {
                    Console.WriteLine("Message: " + record.GetAnsiString("message"));
                }

                if (record.Id == 2)
                {
                    Console.WriteLine("Message: " + record.GetAnsiString("message"));
                }
            };
            
            trace.Enable(provider);
            
            Task.Factory.StartNew(() => trace.Start());

            Console.WriteLine("Tarce started");
            Console.WriteLine("Press any key to stop");
            Console.ReadKey();
            trace.Stop();
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }
    }
}
```

Now the issues...

1. The ids of the events captured by the lobster consumer are 4 and 5, not the values 1 (info) and 2 (error) set in the methods LogEvent and LogError of the EventTrigger class. 
2. The properties "message" and "ex" exists on those events, but their values are not the ones i passed when they are raised ("some message" and "some exception").

![lobstererror1](https://cloud.githubusercontent.com/assets/2701532/20709296/9b66fce2-b61b-11e6-89f9-11a69d2134c2.png)
![lobstererror2](https://cloud.githubusercontent.com/assets/2701532/20709298/9b78e40c-b61b-11e6-90e2-d903f470e1e0.png)

I used perfview.exe to check if the events are raised by EventTrigger are correct and seems everything is ok:

![image](https://cloud.githubusercontent.com/assets/2701532/20709917/10daa41c-b61f-11e6-9fcd-df38db1121ad.png)
![image](https://cloud.githubusercontent.com/assets/2701532/20709942/2f0bf076-b61f-11e6-8fe8-85599d07b3fe.png)

Is this a bug or am i missing something?

Thanks again.

**Comment by zacbrown** [comment]
I will look into this one today. It may take me a little time.

**Comment by zacbrown** [comment]
Alright - I had some success in understanding the issues you're seeing. Here's the short version:

1. The "message" and "ex" fields you're logging aren't being logged as ANSI strings, they're being logged as Counted Strings. You need to call `record.GetCountedString("message")`
2. I cannot explain why the record.Id fields are wrong **but I was able to confirm that krabsetw is parsing them correctly**. I pulled dumped the events in PerfView and they show the IDs to be 4 and 5 respectively, like you're seeing in krabsetw.

**Long Version**

For the issue of ANSI versus Counted String, this one is hard to identify without using a debug version of the Lobsters DLL (O365.Security.Native.ETW). With the debug version, it will assert under the debugger if you try to call the wrong type-getter on a field. I will open an issue to either create a debug-version of this lobsters or make a multi-configuration nuget package.

Here's an example of the assert:
![typeassert](https://cloud.githubusercontent.com/assets/1295/20771091/e10e6abe-b6fc-11e6-8fdc-0b9177f15eec.png)


For the record ID thing, I'm not sure how to think about that. We don't use `System.Diagnostics.Tracing.EventSource` in our code base so this is the first time I've tried to debug one. Here's what I'm seeing under PerfView when I dump the events:

**Dumped LogEvent event**
![dumped-info-event](https://cloud.githubusercontent.com/assets/1295/20771126/0845b204-b6fd-11e6-826c-110d5da23270.PNG)

**Dumped LogError event**
![dumped-error-event](https://cloud.githubusercontent.com/assets/1295/20771154/1969deac-b6fd-11e6-8e56-0f3dbf89d68c.PNG)

**Comment by zacbrown** [comment]
Debug version of O365.Security.Native.ETW available now as NuGet package: https://www.nuget.org/packages/O365.Security.Native.ETW.Debug/1.0.0.

This will produce the type asserts I screen-shotted above.

**Comment by zacbrown** [comment]
Please let me know if you're still having trouble. If I don't hear from you I'll close the issue on Friday.
