### ISSUE TITLE
Feedback for Windows diagnostics team about Event Viewer UI improvements

### ISSUE THREAD

**Issue by kasper3** [Microsoft/krabsetw#47]
Hello, I know this isn't the repository by Windows / TechNET diagnostics team, yet I would like to share some thoughts on the user experience. I hope this community feedback will be forwarded to the internal team responsible for Event Viewer.

In year 2018, if we look at Event Viewer UI and compare it to other products like [Seq](https://getseq.net/) (a Windows service, that provides an interactive web interface with useful controls):

![Seq screenshot](https://camo.githubusercontent.com/69eb2567437c661de795092c2cf36932e39f8f8a/68747470733a2f2f6e626c756d68617264742e6769746875622e696f2f696d616765732f7365712d73696e6b2d73637265656e73686f742e706e67)

turns out that Event Viewer is not only slow in delivering relevant information in time (load, refresh, search timing) but lacks very many rich usability features that renders it a past-century product.

Please consider introducing a new UI for Event Viewer, preferably a Web-based product reachable by intr[ae]nets with Windows auth etc. If web is not an option, new WPF based viewer will be equally welcome!

Thanks!

**Comment by swannman** [comment]
Thanks @kasper3. The best way to get this feedback to the product team is to use the Feedback Hub: https://support.microsoft.com/en-us/help/27932/windows-10-send-us-feedback

Cheers,
Matt
