### ISSUE TITLE
Doesn't compile under C++17

### ISSUE THREAD

**Issue by nzbart** [Microsoft/krabsetw#50]
I have had to downgrade the Visual Studio C++ compiler to the C++14 standard (`/std:c++14`) to compile because some types, such as `unary_function` have been deprecated in C++17.

Is it possible to update the code to be compatible with the latest version of the Visual Studio C++ compiler?

Note that I'm using the `krabsetw` NuGet package.

**Comment by zacbrown** [comment]
I'll take a stab at it.

**Comment by zacbrown** [comment]
Fixed in #51
