### ISSUE TITLE
Does krabsetw support resolving syscall address and return address in call-stacks?

### ISSUE THREAD

**Issue by rainkin1993** [Microsoft/krabsetw#63]
syscall field in SysCallEnter event is a memory address 
values in the call-stack event are also memory address.

Does krabsetw support resolving syscall and call-stacks?
e.g. 0x12312412312 -> NtCreateFile

**Comment by zacbrown** [comment]
If you have further questions. Please feel free to reopen this issue or create a new one if the topic is different.
