### ISSUE TITLE
Tdh_helpers pointer and size_t support

### ISSUE THREAD

**Issue by zeavi** [microsoft/krabsetw#67]
Hi Zac,
Krabs/Krabs/parser.hpp(251) when callkng parser::parser
With size_t, the function Krabs::debug:: asset_valid_assugnment passing to
Tdh_helpers.hpp throw_if_invalid 
Compares TDH_INTYPE_UINT64 and TDH_INTYPE_POINTER (if event property if pointer)
e.g in page_fault event property: BaseAddress and RegionSize
Thanks alot

**Comment by zacbrown** [comment]
Hi,

Can you provide some sample code. I'm not sure I understand the problem.

thanks,

Zac

**Comment by zacbrown** [comment]
Hi - following up, there's currently no support for TDH_INTYPE_POINTER. We'd need to add it here: https://github.com/Microsoft/krabsetw/blob/0b42d12c337d2ea954ebc89c1547be48a552cf13/krabs/krabs/tdh_helpers.hpp#L153

We'd welcome a PR to add the support or it will be addressed as either the engineering team at MSFT finds time or when I have spare time to fix the issue.

**Comment by pathtofile** [comment]
Turns out I'd also like to cleanly parse the `file_io` provider, which has handles/pointers in it :-)
Put up a MR with an attempt at a sane parsing of POINTER types: https://github.com/microsoft/krabsetw/pull/132/files

**Comment by swannman** [comment]
Merged #132
