### ISSUE TITLE
Linking error with c++ project.

### ISSUE THREAD

**Issue by rushikeshpatil12** [Microsoft/krabsetw#73]
I am seeing below linking error 

unresolved external symbol "private: static class krabs::schema_locator krabs::schema_locator::singleton_" (?singleton_@schema_locator@krabs@@0V12@A)	

My code is only 

#include <iostream>
#include <thread>
#include <vector>
#include <condition_variable>
#include "../packages/Microsoft.O365.Security.Krabsetw.2.0.2/lib/native/include/krabs.hpp"
int main()
{
		const EVENT_RECORD record;
		krabs::schema schema(record);
}

I have installed Nuget package Microsoft.O365.Security.Krabsetw version 2.0.2.
I tried both VS 2017(15.9.9) & 2019.

Appreciate any help.
Cheers.

**Comment by zacbrown** [comment]
@rushikeshpatil12 - Hi, looks like your project isn't being setup correctly? When you add the krabsetw package, it should load this targets file as part of your vcxproj: https://github.com/Microsoft/krabsetw/blob/master/build/native/krabsetw.targets

In either case, the missing piece you need is to include compilation of krabs.cpp: https://github.com/Microsoft/krabsetw/blob/master/krabs/krabs.cpp

**Comment by rushikeshpatil12** [comment]
Thanks Zac. I also noticed targets not being used and so tried reinstalling
nuget multiple times. It seems to be doing the same.

I will try to to manually configure it.

Thanks for showing the direction.

Cheers

**Comment by rushikeshpatil12** [comment]
For the benefit new readers. Added  below import group  to include krabs.cpp. 

<ImportGroup Label="ExtensionTargets">
...

**<Import Project="..\packages\Microsoft.O365.Security.Krabsetw.2.0.2\build\native\krabsetw.targets" Condition="Exists('..\packages\Microsoft.O365.Security.Krabsetw.2.0.2\build\native\krabsetw.targets')" />

..**

  </ImportGroup>

**Comment by swannman** [comment]
Resolving as fixed. Thanks @rushikeshpatil12 for documenting how you were able to resolve this!
