### ISSUE TITLE
File IO provider schema_not_found error!

### ISSUE THREAD

**Issue by ejaz629** [microsoft/krabsetw#76]
Hi Zac,

While logging kernel events for File IO events, I came across the run time error "krabs::could_not_find_schema at memory location ...". Can you please help me to solve this issue?

There are two scenarios:
1. The above error occurs only when the following flag is enabled: **EVENT_TRACE_FLAG_FILE_IO_INIT** in the kernel_providers.hpp at
CREATE_CONVENIENCE_KERNEL_PROVIDER(
		file_init_io_provider,
		EVENT_TRACE_FLAG_FILE_IO_INIT,
		krabs::guids::file_io);

2. If I enable the following flag **EVENT_TRACE_FLAG_DISK_FILE_IO** (and disable the flag EVENT_TRACE_FLAG_FILE_IO_INIT) in kernel_providers.hpp, the program runs fine. I need to enable both the flags to get a wide range of file events. 

After digging into the code, I think (not sure) that the problem occurs when retrieving the cached data in function schema_locator::get_event_schema(const EVENT_RECORD& record) of schema_locator.hpp. It is because it locks certain schema using scope_lock.

**My code is here:**
#include <iostream>
#include <fstream>
#include <thread>
#include <condition_variable>
#include "..\..\krabs\krabs.hpp"
#include "examples.h"
#include <atlstr.h>
#include <Windows.h>
#include <iostream>
#include <stdio.h>
#include <psapi.h>
#include <tlhelp32.h>
#include <fstream>
#include <cstdio>

static void setup_fileio_provider(krabs::kernel::file_io_provider& fileioprovider);
std::ofstream trace_file;

void kernel_trace_001::start()
{
	
        krabs::kernel_trace trace(L"MyMagicTrace");
        trace_file.open ("c:\\mytrace.txt", std::ios::out | std::ios::binary);
	
        krabs::kernel::file_io_provider fileio_provider; 
	krabs::kernel::file_init_io_provider fileioinit_provider;
   	
	setup_fileio_provider(fileio_provider);

	trace.enable(fileio_provider);
	trace.enable(fileioinit_provider); 
	
	trace.start();
       trace_file.close();
}

void setup_fileio_provider(krabs::kernel::file_io_provider& provider) {
	provider.add_on_event_callback([](const EVENT_RECORD &record) {
		krabs::schema schema(record);
		krabs::parser parser(schema);
		
		if ( schema.event_opcode() == 64 ) {
                       std::wstring filename = parser.parse<std::wstring>(L"OpenPath");
			std::uint32_t fileattr = parser.parse<std::uint32_t>(L"FileAttributes");
			std::uint32_t shareaccess = parser.parse<std::uint32_t>(L"ShareAccess");
			std::uint32_t* fileobj = parser.parse<std::uint32_t*>(L"FileObject");
			
			std::wcout << "File " << schema.event_name() << "\t" << schema.timestamp() << "\t" << schema.process_id() << "\t" << schema.thread_id() << "\t" << fileobj << "\t" << shareaccess << "\t" << filename << "\n";
		}
		
		if (schema.event_opcode() == 70 || schema.event_opcode() == 71) 
		{
			std::uint32_t ttid = parser.parse<std::uint32_t>(L"TTID");
			std::uint32_t* filekey = parser.parse<std::uint32_t*>(L"FileKey");
			std::uint32_t* fileobj = parser.parse<std::uint32_t*>(L"FileObject");

			std::wcout << "File " << schema.event_name() << L"\t" << schema.timestamp() << "\t" << schema.process_id() << "\t" << schema.thread_id() << "\t" << filekey << "\t" << fileobj << "\n";
		} 
		
		if (schema.event_opcode() == 32 || schema.event_opcode() == 35 || schema.event_opcode() == 36)
		{
			std::wstring filename = parser.parse<std::wstring>(L"FileName");
			std::uint32_t* fileobj = parser.parse<std::uint32_t*>(L"FileObject");

			std::wcout << "File " << schema.event_name() << "\t" << schema.timestamp() << "\t" << schema.process_id() << "\t" << schema.thread_id() << "\t" << fileobj << "\t" << filename << "\n";
		} 
		
		if (schema.event_opcode() == 68 )
		{
			std::uint32_t ttid = parser.parse<std::uint32_t>(L"TTID");
			std::uint32_t* filekey = parser.parse<std::uint32_t*>(L"FileKey");
			std::uint32_t iosize = parser.parse<std::uint32_t>(L"IoSize");
			std::uint32_t ioflags = parser.parse<std::uint32_t>(L"IoFlags");

			std::wcout << "File " << schema.event_name() << "\t" << schema.timestamp() << "\t" << schema.process_id() << "\t" << ttid << "\t" << filekey << "\n";
		}

	});
}

**Comment by ejaz629** [comment]
Just to add: when the flag **EVENT_TRACE_FLAG_FILE_IO_INIT** is enabled, few events are logged, but after some events (say 20 events), the program crashes with the "krabs::could_not_find_schema at memory location ..." error.

**Comment by zacbrown** [comment]
@ejaz629 - unfortunately, I'm not familiar with that provider. 

The schema cache locking is expected behaviour. I'm not sure I understand the concern with the lock.

The interesting question is why it can't find the schema. *What version of Windows are you testing this code against?*

**Comment by pathtofile** [comment]
Hey @ejaz629 - Do you still see this issue in 2020?
I was recently running an `file_io` and `file_init_io` trace and it seemed to work fine?
The only thing not working from your example is the `parser.parse<std::uint32_t*>(L"FileKey");` stuff , as Krabs doesn't deal with `TDH_INTYPE_POINTER` types, so that will fail a compiler-time check

**Comment by swannman** [comment]
This will be addressed by #132 (thanks @pathtofile!)

**Comment by swannman** [comment]
#132 added support for `TDH_INTYPE_POINTER`, and per the comment above the rest of this scenario is working.
