### ISSUE TITLE
Cross platform and .Net Core Support

### ISSUE THREAD

**Issue by MedAnd** [microsoft/krabsetw#77]
Consider adding cross platform and .Net Core Support. Ideally this will include full support for the new & evolving .Net Core EventCounter design.

I would like to use this high performance library in .Net Core microservices that run on Windows and Linux.

**Comment by swannman** [comment]
Thanks for the suggestion! At this time we are focusing solely on Windows since this library is tightly-coupled to the Windows ETW API.

**Comment by MedAnd** [comment]
Thanks the clarification & have created this request with the .Net Core / CLR team: [High performance, low memory, cross platform .Net Core library for processing diagnostic & trace information](https://github.com/dotnet/diagnostics/issues/380).
