### ISSUE TITLE
Add ability to configure trace performance characteristics

### ISSUE THREAD

**Issue by jdu2600** [microsoft/krabsetw#80]
re: https://github.com/microsoft/krabsetw/blob/master/krabs/krabs/nightmare.hpp#L218

I'd love to be able to configure BufferSize as well as MinimumBuffers, MaximumBuffers and FlushTimer (including via the .NET wrapper) for new traces.  :-)

My trace was dropping events so I was hoping to play with the buffer settings to see if I could resolve this.

**Comment by jdu2600** [comment]
And probably the EVENT_TRACE_NO_PER_PROCESSOR_BUFFERING flag too.

**Comment by zacbrown** [comment]
@jdu2600 - we can look into adding that. 

Some advice if you're dropping events: consider pulling events off the thread as fast as possible and doing your interesting process on a separate thread. 

The thread ETW invokes your callback on is a bottleneck.

**Comment by jdu2600** [comment]
Yes, but you are still limited to 64KB of events per second with the defaults. :-)

I've had a first go at C++ support - https://github.com/jdu2600/krabsetw/tree/performance
C++/CLI to come.

**Comment by jdu2600** [comment]
C++/CLI support pushed.

**Comment by swannman** [comment]
This has been merged in - thank you for implementing this!
