### ISSUE TITLE
krabsetw performance 

### ISSUE THREAD

**Issue by dootyfree** [microsoft/krabsetw#83]
Any ideas on handling memory/performance while performing long running traces.  Wrote an app utilizing a few providers (works great btw, thanks!) and memory just keeps increasing, similar to memory leak.  Not a coder so may be just generally bad code, but how best to manage memory, cpu? After 10hrs are to near 1gb of memory used, steadily increasing....

**Comment by swannman** [comment]
Could you share a minimal repro that demonstrates the leak?

**Comment by dootyfree** [comment]
Not sure what you mean, but do you find this in your implementations?  Has performance ever been an issue?

**Comment by swannman** [comment]
We are not experiencing a memory leak in our use of krabsetw, no. It would be helpful if you could share a sample application that demonstrates the memory leak -- a "minimal repro" would be a project with the smallest number of lines necessary to demonstrate the defect. A good way to approach this is to remove functionality from your existing application in stages until either there is nothing left to remove or the leak disappears.

**Comment by jdu2600** [comment]
Ah. I had a 'friend' with a similar issue once - turns out there was an unhandled exception in a processing thread... and ETW just kept delivering those 64KB buffers every second...

**Comment by swannman** [comment]
Closing this for lack of new information.
