### ISSUE TITLE
Support for x86

### ISSUE THREAD

**Issue by samtatasurya** [microsoft/krabsetw#88]
Hi,

What are the limitations of using native (C++) krabsetw on x86 / 32-bit machine?
The `README` mentioned that:
> krabsetw and Microsoft.O365.Security.Native.ETW only support x64. No effort has been made to support x86.

But I made a simple program compiled for x86 which used native krabsetw, similar to `kernel_trace_001` in `NativeExamples`, and it seemed to work just fine.

Maybe a few bullet points on `README` regarding the internal / implementation limitations of krabsetw on x86 would help to clarify it.

**Comment by swannman** [comment]
Hi Samuel, thanks for sharing that this worked for you. `krabsetw` may indeed work on x86 -- I'm not aware of any specific limitations. However, we haven't tested it and can't commit to fix issues that are x86-only. If x86-only issues arise, we would gladly review and accept PRs for them.

Cheers,
Matt
