### ISSUE TITLE
Remove Boost library dependency

### ISSUE THREAD

**Issue by davemcincork** [microsoft/krabsetw#99]
KrabsETW has a dependency on Boost but only because of a single source file (comparers.hpp). The four Boost-dependent functions in here can be easily re-coded to eliminate the Boost dependency altogether. Moreover, this results in a (marginally) faster implementation. Is this something you could consider doing? The need to download a huge Boost nuget completely unnecessarily is a bit of a turn-off in some projects.

**Comment by swannman** [comment]
Hi Dave, this isn't currently on our roadmap but we'd be happy to review a PR for this if you're willing to submit one.

Cheers,
Matt

**Comment by turingcompl33t** [comment]
Big Boost fan here, but I'm also interested in removing the dependency in Krabs. If you're still willing to review a PR for this issue @swannman, I am prepared to submit one with the functions re-implemented to remove the dependency. All tests are passing currently, but I am open to adding more to the existing suite if you feel this is warranted.

**Comment by swannman** [comment]
@turingcompl33t yes, I'd be willing to review a PR. Thanks for tackling this!

**Comment by turingcompl33t** [comment]
Awesome, thanks @swannman. Just submitted it.

**Comment by davemcincork** [comment]
Thanks, @turingcompl33t. Unfortunately (but understandably given the specific tech sector in which I work) my employer makes it hard for us to contribute to open source projects.

**Comment by swannman** [comment]
Fixed by #126. Thanks @turingcompl33t !
